server:
  port: 8081

spring:
  application:
    name: plcae-api
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/common?serverTimezone=Asia/Seoul&useSSL=false
    username: cmuser
    password: qwer1234!

logging.level:
  org.hibernate.SQL: debug
